spring:
  ai:
    vectorstore:
      chroma:
        initialize-schema: true  # 是否初始化 Chroma 向量存储的模式
        client:
          host: ${CHROMA_HOST:http://192.168.18.64}  # 需要替换为自己的 Chroma 服务地址
          port: ${CHROMA_PORT:8000}  # 需要替换为自己的 Chroma 服务端口
    openai:
      api-key: ${OPENAI_API_KEY:2}
      base-url: ${OPENAI_BASE_URL:https://api.moonshot.cn}
      chat:
        options:
          model: moonshot-v1-8k
---
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/tomato-llm
    username: root
    password: 12345678